---
title: "Untitled"
format: html
---

## Project Checkpoint 1 

### Introduction
My dataset is the [Break Free From Plastic (BFFP)](https://github.com/rfordatascience/tidytuesday/blob/main/data/2021/2021-01-26/readme.mdz) from TidyTuesdays. This dataset looks at plastic waste collected during cleanup events around the world, where volunteers record variables like the country, year, parent company responsible, and counts of different plastic types.

The data comes from Break Free From Plastic global brand audits, which are organized to better understand where plastic pollution is coming from and to hold companies accountable. The dataset I'm using was put together by Sarah Sauve, who combined data from the 2019 and 2020 audits into one dataset. You find it [here](https://github.com/sarahsauve/TidyTuesdays/blob/master/BFFPDashboard/BlogPost.md). 

She also created a blog post and Shiny app describing her data cleaning process and analysis. She made it to contribute to global audit and as a way to understand plastic waste in St. John.

Each row represents a summary of plastic collected for a specific company, in a specific country and year. The values in each row are counts of different types of plastic for each company.

The different types of plastic are numeric, and they can be anywhere from 0 to a few hundred depending on how common the material is.

Here are a few rows of the dataset:
```{r}
library(dplyr)
library(ggplot2)
plastic <- read.csv("~/Documents/R/plastics.csv")
head(plastic, n = 10)
plastic |> dplyr::sample_n(6)

```
### Data Cleaning

Sarah used several cleaning steps to make it usable. The original data came from a bunch of different CSV files from different countries and years, everything had to be combined into one dataset first. For the 2019 data, the country wasn’t included, so it was pulled from the file names and added as a new column. Also, not every country reported all plastic types, so missing columns like HDPE, PET, and more were added and filled with 0s. Some rows like “Grand Total” and entries where the company was listed as “NULL” were removed because they were just summary rows and not actual observations, which could mess up the analysis. The column names were also cleaned up so both years matched, and a year column was added before merging everything together. 

### Explorations

## RQ1
Which parent companies contribute the most to plastic waste across different years?

## RQ2
How does the distribution of plastic types like HDPE, PET, and more differ by country?

## RQ3
How is plastic waste related to a a country’s recycling rate or waste management policies?

## RQ4
Is there a relationship between plastic waste and a countries economic status (devloped vs devloping countries)?